# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hughesdemo.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HughesDemo(object):
    def setupUi(self, HughesDemo):
        HughesDemo.setObjectName("HughesDemo")
        HughesDemo.resize(457, 308)
        self.centralwidget = QtWidgets.QWidget(HughesDemo)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(150, 130, 160, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_go = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_go.setObjectName("button_go")
        self.horizontalLayout.addWidget(self.button_go)
        self.button_stop = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_stop.setObjectName("button_stop")
        self.horizontalLayout.addWidget(self.button_stop)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 30, 291, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        HughesDemo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HughesDemo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 457, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAnimals = QtWidgets.QMenu(self.menubar)
        self.menuAnimals.setObjectName("menuAnimals")
        HughesDemo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HughesDemo)
        self.statusbar.setObjectName("statusbar")
        HughesDemo.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(HughesDemo)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(HughesDemo)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCut = QtWidgets.QAction(HughesDemo)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(HughesDemo)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(HughesDemo)
        self.actionPaste.setObjectName("actionPaste")
        self.actionVibrate = QtWidgets.QAction(HughesDemo)
        self.actionVibrate.setObjectName("actionVibrate")
        self.actionJump_up_and_Down = QtWidgets.QAction(HughesDemo)
        self.actionJump_up_and_Down.setObjectName("actionJump_up_and_Down")
        self.actionPine_Marten = QtWidgets.QAction(HughesDemo)
        self.actionPine_Marten.setObjectName("actionPine_Marten")
        self.actionWombat = QtWidgets.QAction(HughesDemo)
        self.actionWombat.setObjectName("actionWombat")
        self.actionCoatimund = QtWidgets.QAction(HughesDemo)
        self.actionCoatimund.setObjectName("actionCoatimund")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuAnimals.addAction(self.actionPine_Marten)
        self.menuAnimals.addAction(self.actionWombat)
        self.menuAnimals.addAction(self.actionCoatimund)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAnimals.menuAction())
        self.label.setBuddy(self.lineEdit)
        self.label_2.setBuddy(self.lineEdit_2)

        self.retranslateUi(HughesDemo)
        self.actionQuit.triggered.connect(HughesDemo.close)
        self.button_go.pressed.connect(self.lineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(HughesDemo)
        HughesDemo.setTabOrder(self.button_stop, self.lineEdit_2)
        HughesDemo.setTabOrder(self.lineEdit_2, self.button_go)
        HughesDemo.setTabOrder(self.button_go, self.lineEdit)

    def retranslateUi(self, HughesDemo):
        _translate = QtCore.QCoreApplication.translate
        HughesDemo.setWindowTitle(_translate("HughesDemo", "MainWindow"))
        self.button_go.setToolTip(_translate("HughesDemo", "Make things go"))
        self.button_go.setText(_translate("HughesDemo", "Go"))
        self.button_stop.setToolTip(_translate("HughesDemo", "Make things stop"))
        self.button_stop.setText(_translate("HughesDemo", "Stop"))
        self.label.setText(_translate("HughesDemo", "First name"))
        self.label_2.setText(_translate("HughesDemo", "Last Name"))
        self.menuFile.setTitle(_translate("HughesDemo", "File"))
        self.menuEdit.setTitle(_translate("HughesDemo", "Edit"))
        self.menuAnimals.setTitle(_translate("HughesDemo", "Animals"))
        self.actionOpen.setText(_translate("HughesDemo", "Open..."))
        self.actionQuit.setText(_translate("HughesDemo", "Quit"))
        self.actionCut.setText(_translate("HughesDemo", "Cut"))
        self.actionCopy.setText(_translate("HughesDemo", "Copy"))
        self.actionPaste.setText(_translate("HughesDemo", "Paste"))
        self.actionVibrate.setText(_translate("HughesDemo", "Vibrate"))
        self.actionJump_up_and_Down.setText(_translate("HughesDemo", "Jump up and Down"))
        self.actionPine_Marten.setText(_translate("HughesDemo", "Pine Marten"))
        self.actionWombat.setText(_translate("HughesDemo", "Wombat"))
        self.actionCoatimund.setText(_translate("HughesDemo", "Coatimundi"))
